### ISSUE TITLE
Laravel Mix

### ISSUE THREAD

**Issue by Reaper45** [jessedc/laravel-heroku-example#1]
@jessedc What if you are using laravel mix. Whats is the setup?

**Comment by jessedc** [comment]
Hey @Reaper45,

If you want the deployment process to build your javascript assets you'll want to make sure your heroku app has the `heroku/nodejs` buildpack along side `heroku/php`. 

You should then add a "postinstall" script to your package.json that runs your laravel mix production script. 

For example:

```
 "scripts": {
    ...
    "production": "NODE_ENV=production webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js && php artisan build:email",
    "postinstall": "npm run production"
  },
```

The nodejs buildpack it will pickup the package.json file and run `npm run postinstall` automatically on deployment as documented [here](https://devcenter.heroku.com/articles/nodejs-support).

Hope that helps!

**Comment by diegocam** [comment]
The problem with this is that when you run `npm i` locally for development, it will run `npm run production`, so then youre stuck with your app running in a `production` environment, unless you run an extra step to manually run it in dev.

**Comment by jessedc** [comment]
@diegocam you're right, but you often don't need to run `npm i` in development too often. The trade off is with this config is you don't have to run an additional step on deployment. I  tend to use `npm run watch` in development to spin up the live reloading.

**Comment by eloyesp** [comment]
Now you can use `build` or `heroku-postbuild` instead of `postinstall` to run the build on heroku. ([source](https://devcenter.heroku.com/articles/nodejs-support#build-behavior))
